"""Add api_symbol to investment_transactions

Revision ID: 0d6ca885ece1
Revises: 36a502940a86
Create Date: 2025-10-26 01:11:33.801026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6ca885ece1'
down_revision: Union[str, Sequence[str], None] = '36a502940a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_transactions', sa.Column('api_symbol', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment_transactions', 'api_symbol')
    # ### end Alembic commands ###
