"""
Generate an Alembic migration that removes a predefined category, repointing
every FK reference to a replacement category first.

Category rows are protected by RESTRICT FKs — a naive DELETE fails on any DB
with FK enforcement on (Postgres prod; SQLite dev with `PRAGMA foreign_keys`).
This script writes a migration that:

  1. Repoints every table column that FKs into ``categories.id`` from the old
     row to the replacement row.
  2. Deletes the now-unreferenced old row.

The generated migration is then applied via ``alembic upgrade head`` like any
other. The workflow:

    # 1. Generate the migration
    python scripts/remove_category.py <OLD_UUID> <REPLACEMENT_UUID>

    # 2. Edit src/constants/categories.py to remove the old entry.

    # 3. Apply
    alembic upgrade head

Usage:
    python scripts/remove_category.py OLD_UUID REPLACEMENT_UUID [--message TEXT]

Notes:
- The replacement UUID must exist in the DB at migration-run time. In practice
  that means it's either an untouched predefined category or another row being
  added in an earlier migration.
- Removing a parent category: first remove each of its subcategories (one
  migration per sub, or hand-edit the generated file to batch them), then a
  final migration to remove the now-childless parent.
- Downgrade is intentionally a no-op: we don't know the original row's name
  without asking for it. Restore from backup if you need to revert.
"""
from __future__ import annotations

import argparse
import re
import sys
import uuid
from datetime import datetime
from pathlib import Path

# Every table column that references categories.id. Keep this in sync with
# the FK declarations in alembic/versions/36a502940a86_initial_migration.py.
# If a future migration adds another referrer, add it here.
REFERENCING_COLUMNS: list[tuple[str, str]] = [
    ("transactions", "category_id"),
    ("transactions", "subcategory_id"),
    ("transaction_split_allocations", "category_id"),
    ("transaction_split_allocations", "subcategory_id"),
    ("budget_template_categories", "category_id"),
    ("budget_template_categories", "subcategory_id"),
    ("financial_plan_expenses", "category_id"),
    ("categories", "parent_category_id"),
]


def _valid_uuid(s: str) -> str:
    try:
        return str(uuid.UUID(s))
    except ValueError:
        raise argparse.ArgumentTypeError(f"not a valid UUID: {s!r}")


def _find_head_revision(versions_dir: Path) -> str:
    """Scan alembic/versions/ and return the revision ID that nobody uses as
    their ``down_revision`` — i.e. the current head of the migration chain."""
    revisions: set[str] = set()
    down_revisions: set[str] = set()

    rev_re = re.compile(r"^revision:\s*str\s*=\s*['\"]([^'\"]+)['\"]", re.M)
    down_re = re.compile(r"^down_revision.*?=\s*['\"]([^'\"]+)['\"]", re.M)

    for path in versions_dir.glob("*.py"):
        text = path.read_text(encoding="utf-8")
        rm = rev_re.search(text)
        dm = down_re.search(text)
        if rm:
            revisions.add(rm.group(1))
        if dm:
            down_revisions.add(dm.group(1))

    heads = revisions - down_revisions
    if len(heads) != 1:
        raise RuntimeError(
            f"Expected exactly one alembic head, found {len(heads)}: {heads}. "
            "Resolve branched migrations before running this script."
        )
    return heads.pop()


def _slugify(msg: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", msg.lower()).strip("_")[:60] or "remove_category"


MIGRATION_TEMPLATE = '''"""{message}

Revision ID: {new_rev}
Revises: {down_rev}
Create Date: {created}

Generated by scripts/remove_category.py — repoints every FK referrer of the
old category to the replacement, then deletes the old row.

After this migration runs, remember to remove the corresponding entry from
``src/constants/categories.py`` if you haven't already.
"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import text


revision: str = '{new_rev}'
down_revision: Union[str, Sequence[str], None] = '{down_rev}'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


OLD_UUID = '{old_uuid}'
REPLACEMENT_UUID = '{replacement_uuid}'


# Every table column that FKs into categories.id. Kept in sync by
# scripts/remove_category.py at generation time.
_REFERRERS = {referrers!r}


def upgrade() -> None:
    """Repoint references from OLD_UUID to REPLACEMENT_UUID, then delete OLD_UUID."""
    bind = op.get_bind()

    # Resolve both UUIDs to integer ids (categories.id is the FK target).
    row = bind.execute(text(
        "SELECT id FROM categories WHERE uuid = :u"
    ), {{"u": OLD_UUID}}).first()
    if row is None:
        # Idempotent: the target category is already gone. Nothing to do.
        return
    old_id = row[0]

    row = bind.execute(text(
        "SELECT id FROM categories WHERE uuid = :u"
    ), {{"u": REPLACEMENT_UUID}}).first()
    if row is None:
        raise RuntimeError(
            f"Replacement category {{REPLACEMENT_UUID}} not found; cannot repoint. "
            "Add it via a predefined-categories migration first."
        )
    new_id = row[0]

    # Repoint every referrer
    for table, column in _REFERRERS:
        bind.execute(
            text(f"UPDATE {{table}} SET {{column}} = :new_id WHERE {{column}} = :old_id"),
            {{"new_id": new_id, "old_id": old_id}},
        )

    # Now safe to delete
    bind.execute(text("DELETE FROM categories WHERE id = :old_id"), {{"old_id": old_id}})


def downgrade() -> None:
    """Intentional no-op — the deleted category's original name/parent are
    not preserved by this migration. Restore from backup if needed."""
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    parser.add_argument("old_uuid", type=_valid_uuid, help="UUID of the category to remove")
    parser.add_argument("replacement_uuid", type=_valid_uuid,
                        help="UUID of the category that should receive the old row's references")
    parser.add_argument("--message", "-m",
                        default=None,
                        help="Human-readable migration message (default: 'remove category <old> -> <replacement>')")
    args = parser.parse_args()

    if args.old_uuid == args.replacement_uuid:
        print("ERROR: old and replacement UUIDs are identical — nothing to do.", file=sys.stderr)
        return 2

    repo_root = Path(__file__).resolve().parent.parent
    versions_dir = repo_root / "alembic" / "versions"
    if not versions_dir.exists():
        print(f"ERROR: {versions_dir} does not exist", file=sys.stderr)
        return 2

    try:
        head = _find_head_revision(versions_dir)
    except RuntimeError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2

    new_rev = uuid.uuid4().hex[:12]
    message = args.message or f"remove category {args.old_uuid} -> {args.replacement_uuid}"
    slug = _slugify(message)
    created = datetime.now().isoformat(timespec="seconds")

    body = MIGRATION_TEMPLATE.format(
        message=message,
        new_rev=new_rev,
        down_rev=head,
        created=created,
        old_uuid=args.old_uuid,
        replacement_uuid=args.replacement_uuid,
        referrers=REFERENCING_COLUMNS,
    )

    out_path = versions_dir / f"{new_rev}_{slug}.py"
    if out_path.exists():
        print(f"ERROR: refusing to overwrite {out_path}", file=sys.stderr)
        return 2
    out_path.write_text(body, encoding="utf-8")

    print(f"Wrote migration: {out_path.relative_to(repo_root)}")
    print(f"  revision:     {new_rev}")
    print(f"  down_revision: {head}")
    print()
    print("Next steps:")
    print("  1. Review the migration.")
    print("  2. Remove the old entry from src/constants/categories.py.")
    print("  3. Run: alembic upgrade head")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
